site_name: DMFF
nav:
nav:
  - Home: index.md
  - User Guide:
    - 1. Introduction: user_guide/introduction.md
    - 2. Installation: user_guide/installation.md
    - 3. Basic usage: user_guide/usage.md
    - 4. XML format force field: user_guide/xml_spec.md
    - 5. Theory: user_guide/theory.md  

  - Developer Guide:
    - 1. Introduction: dev_guide/introduction.md
    - 2. Software architecture: dev_guide/arch.md
    - 3. Coding conventions: dev_guide/convention.md
    - 4. Document Writing: dev_guide/write_docs.md

  - Modules:
    - ADMP: 
      - Introduction: admp/readme.md
      - Frontends: admp/frontend.md

  - API: refs/

  - About: 
    - License: license.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:


extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
