name: Feature request
description: Suggest an idea for DMFF.
title: "[Feature Request] _Replace with Title_"
labels: enhancement
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Please provide a brief and concise description of the suggested feature or change"
      placeholder: 
      value:
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: "Please explain why you think this feature is important and should be implemented. If possible, provide references to relevant background information like publications or web pages, and whether you are planning to implement the enhancement yourself or would like to participate in the implementation. If applicable add a reference to an existing bug report or issue that this will address."
      placeholder: 
      value:
    validations:
      required: true
  - type: textarea
    id: solutions
    attributes:
      label: Suggested Solutions
      description: "Please describe possible solutions to the problem. If you have a specific idea in mind, please describe it here. If you don't have a specific idea, please describe what you think would be a good solution to the problem."
      placeholder: 
      value:
    validations:
      required: false
  - type: textarea
    id: further
    attributes:
      label: Further Information, Files, and Links
      description: Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications. If you have any further questions, please don't hesitate to ask them here. Any comments are welcomed!
      placeholder: 
      value:
    validations:
      required: false
